[project]
name = "comfyui-polymask"
description = "ComfyUI nodes for loading images and drawing polygon masks interactively on them with a polygon lasso style tool"
version = "1.0.4"
license = { file = "LICENSE" }
dependencies = ["numpy", "torch"]

[project.urls]
Repository = "https://github.com/Carasibana/ComfyUI-PolyMask"

[tool.comfy]
PublisherId = "carasibana"
DisplayName = "ComfyUI-PolyMask"
Icon = "https://raw.githubusercontent.com/Carasibana/ComfyUI-PolyMask/main/assets/icon-polymask.svg"